In [ ]:
BATTERY DATA ANALYTICS

Given Data

In [3]:
# Smart Electric Vehicle Battery Performance Analysis
battery_sensor_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

TASK - 1: Analysis Using Python Basics

In [4]:
# 1. Display Sensor Readings
print("Battery Sensor Data:")
for data in battery_sensor_data:
    print(data)

Battery Sensor Data:
[0, 32, 400, 20, 95]
[1, 35, 395, 22, 88]
[2, 38, 390, 25, 80]
[3, 40, 385, 28, 70]
[4, 42, 380, 30, 60]
[5, 45, 375, 32, 48]


In [5]:
# 2. Identify High Temperature (If T > 40°C)
print("Temperature Readings and Status:")
for data in battery_sensor_data:
    T = data[1]
    if T > 40:
        print(f"{data[0]}th Hour: High Temperature Alert")
    else:
        print(f"{data[0]}th Hour: Temperature Normal")

Temperature Readings and Status:
0th Hour: Temperature Normal
1th Hour: Temperature Normal
2th Hour: Temperature Normal
3th Hour: Temperature Normal
4th Hour: High Temperature Alert
5th Hour: High Temperature Alert


In [6]:
# 3. Identify Low Battery (If C < 50%)
print("Battery Readings and Status:")
for data in battery_sensor_data:
    C = data[4]
    if C < 50:
        print(f"{data[0]}th Hour: Low Battery Alert")
    else:
        print(f"{data[0]}th Hour: Battery Charge Normal")

Battery Readings and Status:
0th Hour: Battery Charge Normal
1th Hour: Battery Charge Normal
2th Hour: Battery Charge Normal
3th Hour: Battery Charge Normal
4th Hour: Battery Charge Normal
5th Hour: Low Battery Alert


In [7]:
# 4. Return Battery Status
# High - C > 70%
# Medium - 50 <= C <= 70%
# Low - C < 50%
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"
print("Battery Status:")
for data in battery_sensor_data:
    C = data[4]
    print(f"{data[0]}th Hour: {battery_status(C)}")

Battery Status:
0th Hour: High
1th Hour: High
2th Hour: High
3th Hour: Medium
4th Hour: Medium
5th Hour: Low


TASK - 2: Analysis Using NumPy

In [ ]:
#Converting Battery Data To Numpy Array
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

In [8]:
#1. Find Shape Of Array
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(f"Shape of Array: {np.shape(D)}")

Shape of Array: (6, 4)


In [9]:
#2. Calculate Average Of Each Parameter
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(f"Average Temperature: {np.mean(D[:,0])}")
print(f"Average Voltage: {np.mean(D[:,1])}")
print(f"Average Current: {np.mean(D[:,2])}")
print(f"Average Charge: {np.mean(D[:,3])}")

Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


In [10]:
#3. Find Maximum And Minimum Temperature
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(f"Maximum Temperature: {np.max(D[:,0])}")
print(f"Minimum Temperature: {np.min(D[:,0])}")

Maximum Temperature: 45
Minimum Temperature: 32


In [11]:
#4. Extract Voltage Column
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(f"Voltage Column: {D[:,1]}")

Voltage Column: [400 395 390 385 380 375]


In [12]:
#5. Identify High Temperature Readings (T > 40°C)
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print("High Temperature Readings:")
for i in D:
  if i[0] > 40:
    print(i[0])

High Temperature Readings:
42
45


In [13]:
#6. Identify Low Battery Readings (C < 50%)
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print("Low Battery Readings:")
for i in D:
  if i[3] < 50:
    print(i[3])

Low Battery Readings:
48


TASK - 3: ANALYSIS USING LINEAR ALGEBRA

In [14]:
#Transformation Matrix
import numpy as np
A = np.array([
    [2,1],
    [1,3]
])
#Sensor Input
X = np.array([
    [40],
    [25]
])
#Output Y = AX
print(f"Battery Stress Index (Resulting Vector Y): \n {np.dot(A,X)}")

Battery Stress Index (Resulting Vector Y): 
 [[105]
 [115]]


In [15]:
#1. Transpose
import numpy as np
A = np.array([
    [2,1],
    [1,3]
])
print(f"Transpose:\n {A.T}")

Transpose:
 [[2 1]
 [1 3]]


In [16]:
#2. Determinant
import numpy as np
A = np.array([
    [2,1],
    [1,3]
])
print(f"Determinant: {np.linalg.det(A)}")

Determinant: 5.000000000000001


In [17]:
#3. Inverse
import numpy as np
A = np.array([
    [2,1],
    [1,3]
])
print(f"Inverse:\n {np.linalg.inv(A)}")

Inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]


In [18]:
#3. Solve Equations (2x + y = 100, x + 3y = 120)
import numpy as np
A = np.array([
    [2,1],
    [1,3]
])
B = np.array([
    [100],
    [120]
])
print(f"Solution: \n {np.linalg.solve(A,B)}")
print(f"Solution for 'x': {np.linalg.solve(A,B)[0][0]}")
print(f"Solution for 'y': {np.linalg.solve(A,B)[1][0]}")

Solution: 
 [[36.]
 [28.]]
Solution for 'x': 36.0
Solution for 'y': 28.0


TASK - 4: ANALYSIS USING CALCULUS

In [ ]:
#Battery Charge Function C(t)
def C(t):
    return 100 - 2*t - 0.5*t**2

In [19]:
#1. Rate Of Change Of Battery Charge dC/dt
import sympy as sp
def C(t):
    return 100 - 2*t - 0.5*t**2
t = sp.symbols('t')
charge_func = C(t)
dC_dt = sp.diff(charge_func, t)
print("C(t) =", charge_func)
print("dC/dt =", dC_dt)


C(t) = -0.5*t**2 - 2*t + 100
dC/dt = -1.0*t - 2


In [20]:
#2. Calculate Discharge Rate At t = 2 And t = 5
import sympy as sp
def C(t):
    return 100 - 2*t - 0.5*t**2
t = sp.symbols('t')
charge_func = C(t)
dC_dt = sp.diff(charge_func, t)
rate_t2 = dC_dt.subs(t, 2)
rate_t5 = dC_dt.subs(t, 5)
print("Discharge rate at t = 2:", rate_t2)
print("Discharge rate at t = 5:", rate_t5)

Discharge rate at t = 2: -4.00000000000000
Discharge rate at t = 5: -7.00000000000000


In [21]:
#3. Interpret The Result
#Losing Charge At Constant/Increasing/Decreasing Rate
import sympy as sp
def C(t):
    return 100 - 2*t - 0.5*t**2
t = sp.symbols('t')
charge_func = C(t)
dC_dt = sp.diff(charge_func, t)
rate_t2 = dC_dt.subs(t, 2)
rate_t5 = dC_dt.subs(t, 5)
if abs(float(rate_t5)) > abs(float(rate_t2)):
    print("The battery is losing charge at an increasing rate.")
elif abs(float(rate_t5)) < abs(float(rate_t2)):
    print("The battery is losing charge at a decreasing rate.")
else:
    print("The battery is losing charge at a constant rate.")

The battery is losing charge at an increasing rate.
